### ISSUE TITLE
Validate IPN calls

### ISSUE THREAD

**Issue by skorokithakis** [lovvskillz/django-globee#10]
Since GloBee doesn't authenticate its IPN calls, anyone who guesses that the app uses this library can send a fake IPN to the endpoint and mark their payment as completed. Would it be possible for this library to automatically confirm the payment data with GloBee when an IPN comes in, thus making entirely sure that the payment is legitimate, at least until GloBee start signing their IPN calls?

**Comment by lovvskillz** [comment]
Thanks for the issue. I will add an automatic check.

For now you can verify the IPN by yourself.
There is an example: ["if you don't trust the ipn response, you can also get the payment data from GloBee"](https://github.com/lovvskillz/django-globee/blob/master/docs/README.md#get-globee-ipn-signal)

**Comment by skorokithakis** [comment]
Yes, I saw that and I was going to do it, but then I thought it would be better if the library did it automatically so you could be sure the IPN was validated when you got it. Thank you!

**Comment by lovvskillz** [comment]
use the new version `1.5.0` and add this line to your `settings.py`
```python
GLOBEE_AUTO_VERIFY = True
```

**Comment by skorokithakis** [comment]
That's great, thanks!
